### ISSUE TITLE
Create a script for JSON object generation without GOLD ID.

### ISSUE THREAD

**Issue by hubin-keio** [microbiomedata/WorkflowPlanning#31]
The current JSON objects generation relies on GOLD ID and new script is needed so that we can generate JSON objects from external sources that do not have GOLD IDs. An example use case to is to generate JSONs from SRA data analysis results.

**Comment by hubin-keio** [comment]
A related ticket:

Transform EMP study & biosample records from GOLD API for ingest [#294](https://github.com/microbiomedata/nmdc-schema/issues/294)

**Comment by ssarrafan** [comment]
@Michal-Babins and @hubin-keio do you have any updates on this issue?  I am trying to close out the sprint on time since I'll be off next week.  Thanks for your help.

**Comment by Michal-Babins** [comment]
This issue was solved by registering EMP through GOLD. This will be an on going discussion for the coming months. Not sure if we should close this and make a more general ticket for the team, or to keep it open for now. The analysis json will depend on where the data is coming from, these external data sources may very well increase. So, sorry for responding with more questions, but not as clear as creating a script for JSON generation.

**Comment by ssarrafan** [comment]
Sounds like this issue is solved with the registration through GOLD.  I'll close this one but let me know if I can help open additional issues as follow cup items.
